# Generated by Django 4.2.1 on 2023-06-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topfive', '0002_alter_footballclubs_options_footballclubs_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryleagues',
            options={'ordering': ['id'], 'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AddField(
            model_name='footballmatches',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='topfive.seasons', verbose_name='Сезон'),
        ),
    ]
