# Generated by Django 4.2.1 on 2023-06-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topfive', '0003_alter_countryleagues_options_footballmatches_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltables',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='topfive.seasons', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='footballmatches',
            name='guests_goals',
            field=models.IntegerField(verbose_name='забито гостями'),
        ),
    ]
