# Generated by Django 4.2.1 on 2023-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topfive', '0004_totaltables_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryleagues',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/%Y/%m/%d/', verbose_name='Логотип'),
        ),
    ]
